# Generated by Django 5.0.9 on 2026-08-21 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nib', models.CharField(max_length=30, unique=True, verbose_name='NIB (Nomor Induk Berusaha)')),
                ('npwp', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('modal_disetor', models.BigIntegerField(default=0, help_text='Modal disetor dalam Rupiah')),
                ('penghasilan_tahunan', models.BigIntegerField(default=0, help_text='Penghasilan brutro tahunan dalam Rupiah')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('izin_usaha', 'Izin Usaha'), ('sbu', 'SBU (Sertifikat Badan Usaha)'), ('pengalaman_kerja', 'Pengalaman Kerja'), ('sertifikasi', 'Sertifikasi'), ('sdm', 'Sumber Daya Manusia')], max_length=30)),
                ('name', models.CharField(help_text='Nama izin / sertifikat / proyek', max_length=200)),
                ('number', models.CharField(blank=True, default='', help_text='Nomor izin / sertifikat', max_length=100)),
                ('kbli_code', models.CharField(blank=True, default='', help_text='Kode KBLI (untuk SBU)', max_length=10)),
                ('klasifikasi_usaha', models.CharField(blank=True, choices=[('kecil', 'Kecil'), ('menengah', 'Menengah'), ('besar', 'Besar')], default='', max_length=20)),
                ('value_amount', models.BigIntegerField(default=0, help_text='Nilai HPS max / modal / kontrak (Rp)')),
                ('project_name', models.CharField(blank=True, default='', help_text='Nama proyek (untuk pengalaman kerja)', max_length=300)),
                ('client_name', models.CharField(blank=True, default='', help_text='Nama klien (untuk pengalaman kerja)', max_length=200)),
                ('project_year', models.IntegerField(default=0, help_text='Tahun proyek (untuk pengalaman kerja)')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Kedaluwarsa'), ('needs_renewal', 'Perlu Diperbarui')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='companies.companyprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['company', 'category'], name='companies_c_company_312ade_idx')],
            },
        ),
    ]
