# Generated by Django 5.0.9 on 2026-08-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyqualification',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (dynamic fields)'),
        ),
        migrations.AddField(
            model_name='companyqualification',
            name='kbli_codes',
            field=models.JSONField(blank=True, default=list, help_text='Multiple KBLI codes, e.g. ["62019","62090"]'),
        ),
        migrations.AlterField(
            model_name='companyqualification',
            name='kbli_code',
            field=models.CharField(blank=True, default='', help_text='Kode KBLI (legacy, single)', max_length=10),
        ),
    ]
