-- ============================================================
-- SPSE Crawler — Full Seed Data (v0.0.4)
-- Generated from local database
-- Jalankan: psql -U spse_user -d spse_crawler -f seed.sql
-- ============================================================

-- KBLI Master
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('46100', 'Perdagangan Besar Atas Dasar Balas Jasa (Fee) Atau Kontrak', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('46511', 'Perdagangan Besar Komputer dan Perlengkapan Komputer', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('46512', 'Perdagangan Besar Piranti Lunak', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('46521', 'Perdagangan Besar Suku Cadang Elektronik', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('46523', 'Perdagangan Besar Peralatan Telekomunikasi', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('58200', 'Penerbitan piranti lunak (Software)', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('62019', 'Aktivitas Pemrograman Komputer Lainnya', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('62029', 'Aktivitas Konsultasi Komputer dan Manajemen Fasilitas Komputer Lainnya', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;
INSERT INTO web_kbli_master (code, name, is_active) VALUES ('62090', 'Aktivitas Teknologi Informasi Dan Jasa Komputer Lainnya', TRUE) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, is_active=EXCLUDED.is_active;

-- Companies
INSERT INTO companies_companyprofile (name, nib, npwp, address, phone, email, contact_person, modal_disetor, penghasilan_tahunan, is_active, created_at, updated_at) VALUES ('PT Khatulistiwa Nusantara Indonesia', '0220208762392', '0823955182421000', 'Jl. Flamboyan Raya No.39, Kelurahan Cibabat, Kecamatan Cimahi Utara, Kota Cimahi.', '02220668202', 'admin@khansia.co.id', 'Sugeng Pramono', 1000000000, 4000000000, TRUE, NOW(), NOW()) ON CONFLICT (nib) DO UPDATE SET name=EXCLUDED.name, npwp=EXCLUDED.npwp, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, contact_person=EXCLUDED.contact_person, modal_disetor=EXCLUDED.modal_disetor, penghasilan_tahunan=EXCLUDED.penghasilan_tahunan, is_active=EXCLUDED.is_active;
INSERT INTO companies_companyprofile (name, nib, npwp, address, phone, email, contact_person, modal_disetor, penghasilan_tahunan, is_active, created_at, updated_at) VALUES ('PT Solusi Informatika Bersama', 'NIB-PT002', '88.777.666.5-444.002', 'Jl. Gatot Subroto No. 38, Jakarta Pusat', '021-31906060', 'contact@siberinsan.co.id', 'Dewi Kartika', 10000000000, 55000000000, TRUE, NOW(), NOW()) ON CONFLICT (nib) DO UPDATE SET name=EXCLUDED.name, npwp=EXCLUDED.npwp, address=EXCLUDED.address, phone=EXCLUDED.phone, email=EXCLUDED.email, contact_person=EXCLUDED.contact_person, modal_disetor=EXCLUDED.modal_disetor, penghasilan_tahunan=EXCLUDED.penghasilan_tahunan, is_active=EXCLUDED.is_active;

-- Qualifications
INSERT INTO companies_companyqualification (company_id, category, name, number, kbli_codes, details, klasifikasi_usaha, value_amount, project_name, client_name, project_year, status, created_at) VALUES ((SELECT id FROM companies_companyprofile WHERE nib='0220208762392'), 'izin_usaha', 'NIB 2020', '0220208762392', '["46100", "46512", "46521", "58200", "46523", "62019", "46511", "62090", "62029"]', '{}', 'menengah', 1000000000, '', '', 0, 'active', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO companies_companyqualification (company_id, category, name, number, kbli_codes, details, klasifikasi_usaha, value_amount, project_name, client_name, project_year, status, created_at) VALUES ((SELECT id FROM companies_companyprofile WHERE nib='0220208762392'), 'pengalaman_kerja', 'Pengadaan I-SURE System, WPI dan Sales Partnership Enhancement', '', '[]', '{"location": "Jakarta"}', '', 0, 'Pengadaan I-SURE System, WPI dan Sales Partnership Enhancement', 'PT Telkom Indonesia, Tbk', 2026, 'active', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO companies_companyqualification (company_id, category, name, number, kbli_codes, details, klasifikasi_usaha, value_amount, project_name, client_name, project_year, status, created_at) VALUES ((SELECT id FROM companies_companyprofile WHERE nib='0220208762392'), 'sdm', 'Praba', '', '[]', '{"person_name": "Prabaswara Muktikanana Seta", "position": "Project Manager", "education": "s2", "experience_years": 7, "skk": ""}', '', 0, '', '', 0, 'active', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO companies_companyqualification (company_id, category, name, number, kbli_codes, details, klasifikasi_usaha, value_amount, project_name, client_name, project_year, status, created_at) VALUES ((SELECT id FROM companies_companyprofile WHERE nib='0220208762392'), 'sdm', 'Trendy', '', '[]', '{"person_name": "Trendy Dwi Anugrah Gusti", "position": "", "education": "s1", "experience_years": 7, "skk": "Scrum Certified"}', '', 0, '', '', 0, 'active', NOW()) ON CONFLICT DO NOTHING;

-- Users (accounts_user = AUTH_USER_MODEL)
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$6ppOy6CFCBn2dSQNrFVZ5X$JQyk3zI77UBN4h1W7mBxGDiS8pBNuJgZuuYgF3m/3Y0=', NOW(), FALSE, 'superadmin', 'Super', 'Admin', TRUE, TRUE, NOW(), 'superadmin@spse.test', 'superadmin', NULL) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$W3LgYVjPDN7FpVWF2M6Uke$QZbTsK5ZimyWYFP8FLRpDvY8gnQlZd0JF2djJqp5Ayo=', NOW(), FALSE, 'admin', '', '', TRUE, TRUE, NOW(), 'admin@example.com', 'superadmin', NULL) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$FgIsbKtuyOAVQa40uocIam$1N+tnE522LZwo172xZC5YcOeS0tEOOkJ6vOCbbOKWGE=', NOW(), FALSE, 'admin_pt1', 'Sugeng', 'Pramono', TRUE, TRUE, NOW(), 'admin@khansia.co.id', 'company_admin', (SELECT id FROM companies_companyprofile WHERE nib='0220208762392')) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$nf2LWD37UVHVncuDVDhNel$JxM28N6JHUySB6xtyIVFKww/lhN50avkTedhlJmPDIE=', NOW(), FALSE, 'submitter_pt1', 'Budhi', 'Utomo', FALSE, TRUE, NOW(), 'budhi@khansia.co.id', 'submitter', (SELECT id FROM companies_companyprofile WHERE nib='0220208762392')) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$O4IPt2qNJjqqjhQzqoeyAR$g+2MsS0/KQ3ViwPsJD8+aO5hzXu6y7qfEBybLP0uMf4=', NOW(), FALSE, 'admin_pt2', 'Dewi', 'Kartika', TRUE, TRUE, NOW(), 'admin@siberinsan.co.id', 'company_admin', (SELECT id FROM companies_companyprofile WHERE nib='NIB-PT002')) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
INSERT INTO accounts_user (password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, role, company_id) VALUES ('pbkdf2_sha256$720000$7HpgLayKWsxDrWjLTx0PJN$ETVPl645cyIIfyeb0g1Twl+Q30Fw6o4bIMNBjZEz2VI=', NOW(), FALSE, 'submitter_pt2', 'Budi', 'Santoso', FALSE, TRUE, NOW(), 'submitter@siberinsan.co.id', 'submitter', (SELECT id FROM companies_companyprofile WHERE nib='NIB-PT002')) ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password, email=EXCLUDED.email, first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, is_superuser=EXCLUDED.is_superuser, is_staff=EXCLUDED.is_staff, is_active=EXCLUDED.is_active, role=EXCLUDED.role, company_id=EXCLUDED.company_id;
