# Generated by Django 5.0.9 on 2026-08-21 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('web', '0005_add_kbli_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField(default=0, help_text='0-100 percentage fit score')),
                ('summary', models.TextField(default='')),
                ('criteria_json', models.JSONField(default=list, help_text='Array of {requirement, status, evidence, action}')),
                ('llm_provider', models.CharField(default='', max_length=20)),
                ('llm_model', models.CharField(default='', max_length=50)),
                ('token_input', models.IntegerField(default=0)),
                ('token_output', models.IntegerField(default=0)),
                ('cache_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='companies.companyprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='web.tenderresult')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='ai_match_ai_cache_k_538d72_idx')],
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
