# Generated by Django 5.0.9 on 2026-09-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatchresult',
            name='fallback_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='True if generated via fallback engine due to provider error or missing key'),
        ),
    ]
