# Generated by Django 5.0.9 on 2026-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_match', '0002_aimatchresult_fallback_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatchresult',
            name='blockers',
            field=models.JSONField(blank=True, default=list, help_text='List of mandatory requirement failures or blockers'),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='eligibility_status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('CONDITIONALLY_ELIGIBLE', 'Conditionally Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('NOT_READY', 'Not Ready'), ('NOT_APPLICABLE', 'Not Applicable')], db_index=True, default='ELIGIBLE', help_text='Hard qualification eligibility status', max_length=30),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='mandatory_passed',
            field=models.BooleanField(default=True, help_text='True if all hard/mandatory requirements passed'),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='matcher_version',
            field=models.CharField(default='v0.2', help_text='Matcher engine version', max_length=20),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='missing_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of requirements needing evidence or action'),
        ),
        migrations.AddField(
            model_name='aimatchresult',
            name='recommended_actions',
            field=models.JSONField(blank=True, default=list, help_text='Suggested concrete next steps for company'),
        ),
    ]
