# Generated by Django 5.0.9 on 2026-08-21 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('web', '0005_add_kbli_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderSubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum_diproses', 'Belum Diproses'), ('cocok_diproses', 'Cocok & Diproses'), ('sudah_submit', 'Sudah Submit'), ('tidak_cocok', 'Tidak Cocok')], default='belum_diproses', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='companies.companyprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='web.tenderresult')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Status',
                'verbose_name_plural': 'Submission Statuses',
                'ordering': ['-updated_at'],
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
