# Generated by Django 5.0.9 on 2026-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersubmissionstatus',
            name='status',
            field=models.CharField(choices=[('belum_diproses', 'Belum Diproses'), ('cocok_diproses', 'Cocok & Diproses'), ('sudah_submit', 'Sudah Submit'), ('menang', 'Berhasil Menang'), ('gagal', 'Gagal Menang'), ('tidak_cocok', 'Tidak Cocok')], default='belum_diproses', max_length=30),
        ),
    ]
