# Generated by Django 5.0.9 on 2026-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi_input', models.TextField(help_text="Comma-separated instansi codes or 'all'")),
                ('workers', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_packages', models.IntegerField(default=0)),
                ('total_details', models.IntegerField(default=0)),
                ('error_message', models.TextField(default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_instansi', models.CharField(db_index=True, max_length=50)),
                ('id_lelang', models.CharField(db_index=True, max_length=100)),
                ('nama_paket', models.TextField(default='')),
                ('instansi', models.TextField(default='')),
                ('hps', models.BigIntegerField(default=0)),
                ('jenis_pengadaan', models.CharField(default='', max_length=200)),
                ('tahap_saat_ini', models.CharField(default='', max_length=200)),
                ('is_prakualifikasi', models.BooleanField(db_index=True, default=False)),
                ('url_pengumuman', models.URLField(default='')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'unique_together': {('kode_instansi', 'id_lelang')},
            },
        ),
    ]
