# Generated by Django 5.0.9 on 2026-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='satuan_kerja',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tenderresult',
            name='jenis_pengadaan',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenderresult',
            name='tahap_saat_ini',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
