# Generated by Django 5.0.9 on 2026-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tenderresult_satuan_kerja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='kbli_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='kbli_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
