# Generated by Django 5.0.9 on 2026-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_tenderresult_kbli_code_tenderresult_kbli_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='is_it_priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='priority_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
