# Generated by Django 5.0.9 on 2026-08-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_add_kbli_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='tanggal_dibuat',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
