# Generated by Django 5.0.9 on 2026-08-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_add_tanggal_dibuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='requirement_text',
            field=models.TextField(blank=True, default='', help_text='Requirement text from SPSE pengumuman page, stored during crawl'),
        ),
    ]
