# Generated by Django 5.0.9 on 2026-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_add_requirement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresult',
            name='jadwal_json',
            field=models.JSONField(blank=True, default=list, help_text='Array of jadwal tahapan: [{no, tahap, mulai, sampai, perubahan}]'),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='lokasi_pekerjaan',
            field=models.CharField(blank=True, default='', help_text='Work location from detail page', max_length=500),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='metode_pengadaan',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='peserta_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of participants from peserta page'),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='satuan_kerja_detail',
            field=models.CharField(blank=True, default='', help_text='Satuan kerja from detail page', max_length=300),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='syarat_kualifikasi',
            field=models.TextField(blank=True, default='', help_text='Cleaned qualification requirement text from detail page'),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='tahun_anggaran',
            field=models.CharField(blank=True, default='', help_text="Budget year, e.g. '2026'", max_length=20),
        ),
    ]
