# Generated by Django 5.0.9 on 2026-08-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_details_kbli_codes'),
        ('web', '0010_add_tender_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('not_ready', 'Not Ready'), ('stale', 'Stale')], db_index=True, default='not_ready', max_length=20)),
                ('qualification_score', models.IntegerField(default=0, help_text='0-100')),
                ('financial_score', models.IntegerField(default=0, help_text='0-100')),
                ('experience_score', models.IntegerField(default=0, help_text='0-100')),
                ('deadline_score', models.IntegerField(default=0, help_text='0-100')),
                ('strategic_score', models.IntegerField(default=0, help_text='0-100')),
                ('final_score', models.IntegerField(default=0, help_text='0-100, weighted total')),
                ('classification', models.CharField(choices=[('PRIORITAS_TINGGI', 'Prioritas Tinggi'), ('LAYAK_DIKEJAR', 'Layak Dikejar'), ('REVIEW', 'Review'), ('RISIKO_TINGGI', 'Risiko Tinggi'), ('TIDAK_DIREKOMENDASIKAN', 'Tidak Direkomendasikan')], default='TIDAK_DIREKOMENDASIKAN', max_length=30)),
                ('breakdown_json', models.JSONField(blank=True, default=dict, help_text='Explainability data: {components, explanation}')),
                ('calculation_version', models.CharField(default='v0.1', help_text='Scoring formula version used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_scores', to='companies.companyprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_scores', to='web.tenderresult')),
            ],
            options={
                'ordering': ['-final_score'],
                'indexes': [models.Index(fields=['company', 'final_score'], name='web_opportu_company_4b5bb3_idx'), models.Index(fields=['company', 'classification'], name='web_opportu_company_3c0c49_idx')],
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
