# Generated by Django 5.0.9 on 2026-08-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_details_kbli_codes'),
        ('web', '0011_add_opportunity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True)),
                ('ai_matches', models.IntegerField(default=0, help_text='AI match executions today')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_daily_usage', to='companies.companyprofile')),
            ],
            options={
                'ordering': ['-usage_date'],
                'unique_together': {('company', 'usage_date')},
            },
        ),
        migrations.CreateModel(
            name='IntelligenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('AI_MATCH', 'AI Match'), ('OPPORTUNITY_SCORE', 'Opportunity Score')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Number of processed attempts')),
                ('max_attempts', models.IntegerField(default=3)),
                ('priority', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_jobs', to='companies.companyprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_jobs', to='web.tenderresult')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_at', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='web_intelli_status_74c15d_idx'), models.Index(fields=['company', 'status'], name='web_intelli_company_22a0df_idx'), models.Index(fields=['tender', 'company'], name='web_intelli_tender__b27543_idx')],
                'unique_together': {('tender', 'company', 'job_type')},
            },
        ),
    ]
