# Generated by Django 5.0.9 on 2026-08-31 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_intelligencedailyusage_intelligencejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', help_text='Winner company name (external identity only, not auto-linked).', max_length=300)),
                ('winning_value', models.BigIntegerField(blank=True, help_text='Winning / contract value in IDR, when available.', null=True)),
                ('source_url', models.URLField(blank=True, default='', help_text='SPSE page the winner was read from.')),
                ('source_type', models.CharField(default='pemenang_page', help_text='Provenance: which SPSE source produced this record.', max_length=50)),
                ('source_fetched_at', models.DateTimeField(blank=True, help_text='When the source page was fetched.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.OneToOneField(help_text='Tender this winner was awarded for.', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='web.tenderresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Participant company name from SPSE peserta page.', max_length=300)),
                ('npwp', models.CharField(blank=True, default='', help_text='External NPWP identifier from SPSE peserta page.', max_length=50)),
                ('source_url', models.URLField(blank=True, default='', help_text='SPSE page the participant list was read from.')),
                ('source_type', models.CharField(default='peserta_page', help_text='Provenance: which SPSE source produced this record.', max_length=50)),
                ('source_fetched_at', models.DateTimeField(blank=True, help_text='When the source page was fetched.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(help_text='Tender this company participated in.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='web.tenderresult')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tender'], name='web_tenderp_tender__725c06_idx'), models.Index(fields=['npwp'], name='web_tenderp_npwp_f1d115_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenderparticipant',
            constraint=models.UniqueConstraint(fields=('tender', 'name'), name='uniq_tender_participant_name'),
        ),
    ]
