# Generated by Django 5.0.9 on 2026-08-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_tenderwinner_tenderparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderwinner',
            name='alamat',
            field=models.TextField(blank=True, default='', help_text='Winner company address from SPSE pemenang page.'),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='harga_negosiasi',
            field=models.BigIntegerField(blank=True, help_text='Harga Negosiasi (negotiated/final price) in IDR, from SPSE pemenang page.', null=True),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='harga_penawaran',
            field=models.BigIntegerField(blank=True, help_text='Harga Penawaran (offer price) in IDR, from SPSE pemenang page.', null=True),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='harga_terkoreksi',
            field=models.BigIntegerField(blank=True, help_text='Harga Terkoreksi (corrected price) in IDR, from SPSE pemenang page.', null=True),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='npwp',
            field=models.CharField(blank=True, default='', help_text='Winner NPWP from SPSE (may be masked).', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenderwinner',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Winner company name from the SPSE pemenang page (external identity only, not auto-linked).', max_length=300),
        ),
        migrations.AlterField(
            model_name='tenderwinner',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='SPSE page the winner was read from (/evaluasi/{id}/pemenang).'),
        ),
        migrations.AlterField(
            model_name='tenderwinner',
            name='winning_value',
            field=models.BigIntegerField(blank=True, help_text='Final agreed value in IDR = Harga Negosiasi (the negotiated price). See harga_* fields for the full price breakdown.', null=True),
        ),
    ]
