# Generated by Django 5.0.9 on 2026-08-31 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyprofile_npwp_and_more'),
        ('web', '0014_tenderwinner_alamat_tenderwinner_harga_negosiasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderparticipant',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Resolved CompanyProfile for this participant (EXACT match only; never inferred).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='tenderparticipant',
            name='resolution_status',
            field=models.CharField(blank=True, default='', help_text='Entity-resolution match status (EXACT_NPWP / EXACT_OFFICIAL_IDENTIFIER / CANDIDATE_ONLY / IDENTITY_CONFLICT / UNRESOLVED).', max_length=40),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Resolved CompanyProfile for this winner (EXACT match only; never inferred from participant ordering).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='tenderwinner',
            name='resolution_status',
            field=models.CharField(blank=True, default='', help_text='Entity-resolution match status (EXACT_NPWP / EXACT_OFFICIAL_IDENTIFIER / CANDIDATE_ONLY / IDENTITY_CONFLICT / UNRESOLVED).', max_length=40),
        ),
        migrations.AddIndex(
            model_name='tenderparticipant',
            index=models.Index(fields=['company'], name='web_tenderp_company_fac5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderwinner',
            index=models.Index(fields=['company'], name='web_tenderw_company_887ac5_idx'),
        ),
    ]
