# Generated by Django 5.0.9 on 2026-09-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_tenderparticipant_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderresult',
            name='lokasi_pekerjaan',
            field=models.TextField(blank=True, default='', help_text='Work location from detail page'),
        ),
    ]
